[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
solc = "0.8.24"

# RPC Endpoints (use environment variables)
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
anvil = "http://127.0.0.1:8545"

# Etherscan for verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "sepolia" }



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
